plugins {\n    id 'fabric-loom' version '0.10-SNAPSHOT'\n}\n\nrepositories {\n    maven {\n        url = 'https://maven.fabricmc.net/'\n    }\n}\n\ndependencies {\n    minecraft 'com.mojang:minecraft:1.21.11'\n    mappings 'net.fabricmc:fabric-mappings:1.21.11:v2'\n    modCompile 'net.fabricmc:fabric-api:${project.fabric_version}'\n}\n\njava {\n    toolchain {\n        languageVersion = JavaLanguageVersion.of(21)\n    }\n}